//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Input/DefaultActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @DefaultActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @DefaultActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""DefaultActions"",
    ""maps"": [
        {
            ""name"": ""GameLoop"",
            ""id"": ""c762eb36-dc6f-4a27-b552-b6de16750729"",
            ""actions"": [
                {
                    ""name"": ""Position"",
                    ""type"": ""Value"",
                    ""id"": ""e1843518-34fc-4e2d-97f1-3e7c602ce3c1"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""231fad41-a6c2-45ad-8c90-919c77c58bec"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""59d0fdf1-56a6-44aa-a8a4-9f3f4e02f536"",
                    ""path"": ""<Touchscreen>/primaryTouch/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70b65889-89a6-4fc0-a269-243dfe8a16b2"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3122eeb8-64d9-402b-854c-9f1b658592b5"",
                    ""path"": ""<Touchscreen>/primaryTouch/tap"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""82ca99b6-66b9-44ba-98e9-cc9f32881e4a"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GameLoop
        m_GameLoop = asset.FindActionMap("GameLoop", throwIfNotFound: true);
        m_GameLoop_Position = m_GameLoop.FindAction("Position", throwIfNotFound: true);
        m_GameLoop_Click = m_GameLoop.FindAction("Click", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GameLoop
    private readonly InputActionMap m_GameLoop;
    private IGameLoopActions m_GameLoopActionsCallbackInterface;
    private readonly InputAction m_GameLoop_Position;
    private readonly InputAction m_GameLoop_Click;
    public struct GameLoopActions
    {
        private @DefaultActions m_Wrapper;
        public GameLoopActions(@DefaultActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Position => m_Wrapper.m_GameLoop_Position;
        public InputAction @Click => m_Wrapper.m_GameLoop_Click;
        public InputActionMap Get() { return m_Wrapper.m_GameLoop; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameLoopActions set) { return set.Get(); }
        public void SetCallbacks(IGameLoopActions instance)
        {
            if (m_Wrapper.m_GameLoopActionsCallbackInterface != null)
            {
                @Position.started -= m_Wrapper.m_GameLoopActionsCallbackInterface.OnPosition;
                @Position.performed -= m_Wrapper.m_GameLoopActionsCallbackInterface.OnPosition;
                @Position.canceled -= m_Wrapper.m_GameLoopActionsCallbackInterface.OnPosition;
                @Click.started -= m_Wrapper.m_GameLoopActionsCallbackInterface.OnClick;
                @Click.performed -= m_Wrapper.m_GameLoopActionsCallbackInterface.OnClick;
                @Click.canceled -= m_Wrapper.m_GameLoopActionsCallbackInterface.OnClick;
            }
            m_Wrapper.m_GameLoopActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Position.started += instance.OnPosition;
                @Position.performed += instance.OnPosition;
                @Position.canceled += instance.OnPosition;
                @Click.started += instance.OnClick;
                @Click.performed += instance.OnClick;
                @Click.canceled += instance.OnClick;
            }
        }
    }
    public GameLoopActions @GameLoop => new GameLoopActions(this);
    public interface IGameLoopActions
    {
        void OnPosition(InputAction.CallbackContext context);
        void OnClick(InputAction.CallbackContext context);
    }
}
